### PR TITLE
Fix for: Bug with get_heightmap and umap layouts #264

### PR DESCRIPTION
**Pull request by CarloOtano**
Fix for Bug with get_heightmap and umap layouts #264

### CODE REVIEW

**Comment by duhaime** [comment]
Thanks very much for this @CarloOtano! 

So reading through this, it looks like that return you added is missing a few attributes (`n_neighbors`, `min_dist`, `jittered`). 

If you can please add those and verify the change is functioning as expected we should be able to merge this!

**Comment by CarloOtano** [comment]
@duhaime 

As requested I added `n_neighbors`, `min_dist`, `jittered  `in commit ffd8dbfa8702d109c50f4f7feac52a178d061d1e.
Thanks!

**Comment by duhaime** [comment]
@CarloOtano amazing, thanks very much for the quick work!

**Comment by CarloOtano** [comment]
@duhaime Thank you as well!

**Pull request merged**
