### PR TITLE
Multi-thread HDBSCAN; update n_clusters to min_clusters

### PR DESCRIPTION
**Pull request by pleonard212**
Also remove unused k-means module and change description of clustering function

### CODE REVIEW

**Comment by duhaime** [comment]
@pleonard212 thanks for this! 

As it turns out though, we might want to update the `min_clusters` param once more. In the kmeans world, that parameter just made sure the user provided at least n images, where n was the number of clusters kmeans intended to find. In our new HDBSCAN world, `min_cluster_size` is the minimum number of images for a cluster to be considered a cluster. Maybe we should rename the `min_clusters` user param `min_cluster_size` and update the description know what they're setting?

I dig that `core_dist_n_jobs`! I guess [only a small amount of the work can be parallelized](https://github.com/scikit-learn-contrib/hdbscan/issues/131#issuecomment-332699817). Out of curiosity, were you seeing long clustering times on some bigger datasets?

**Comment by pleonard212** [comment]
That sounds good -- do you think both `min_cluster_size` and `min_clusters` are both relevant for exposure to setting via the command line? One interesting side effect of adjusting the latter is causing a large increase in the number of clusters: jumping from 6 to 52, for example, because we're slicing the hierarchy at a lower level when we insist on more clusters. (And of course this dataset-dependent.)

**Comment by duhaime** [comment]
Hmm, I'm confused. Increasing `min_clusters` (which sets the `min_cluster_size` for HDBSCAN) should _decrease_ the number of clusters--are you seeing the opposite behavior?

I think `min_clusters` is a legacy concept and should be removed. But `min_cluster_size` is a valid concept, and users should be able to set that value from the command line ideally. That `min_cluster_size` value should get passed to the HDBSCAN constructor (that is to say, `min_cluster_size` should be a key value pair in the `config` object/dictionary that gets passed to HDBSCAN). Does that make sense?

**Comment by pleonard212** [comment]
Ah yes, I see how it works.  I'll edit and do as you suggest. 

As for the # of clusters changing, I think what happened was I ran `oslomini` once with the implicit default param (`min_cluster_size=20`), which gave us six clusters. Misunderstanding what the option did, I tried `min_cluster_size=7`, which what resulted in 52 clusters being found... since they only had to contain a very few images.

**Comment by duhaime** [comment]
@pleonard212 Woohoo! That makes sense and this looks good! Merging!

**Pull request merged**
